Repository torchbox/m-response, pull requests merged in 2018-10, with the labels that each got.

#3 Add CI config
  .nvmrc
  .travis.yml
  mresponse/frontend/app/yarn.lock
  mresponse/frontend/urls.py
  mresponse/urls.py
  setup.cfg
  vagrant/provision.sh
Labels: needs review

#4 Add basic root and config API views
  .travis.yml
  mresponse/api/__init__.py
  mresponse/api/tests.py
  mresponse/api/urls.py
  mresponse/api/views.py
  mresponse/settings/base.py
  mresponse/urls.py
  requirements.txt
Labels: needs review

#32 Create database on backend tests only
  .travis.yml
Labels: needs review

#33 Add review model
  mresponse/applications/__init__.py
  mresponse/applications/admin.py
  mresponse/applications/migrations/0001_initial.py
  mresponse/applications/migrations/__init__.py
  mresponse/applications/models.py
  mresponse/reviews/__init__.py
  mresponse/reviews/admin.py
  mresponse/reviews/migrations/0001_initial.py
  mresponse/reviews/migrations/__init__.py
  mresponse/reviews/models.py
  mresponse/settings/base.py
  mresponse/utils/__init__.py
  mresponse/utils/android.py
Labels: Back End, needs review

#37 Add response model
  mresponse/responses/__init__.py
  mresponse/responses/admin.py
  mresponse/responses/migrations/0001_initial.py
  mresponse/responses/migrations/__init__.py
  mresponse/responses/models.py
  mresponse/settings/base.py
Labels: Back End

#44 Responder API endpoints
  mresponse/api/tests.py
  mresponse/api/urls.py
  mresponse/api/views.py
  mresponse/applications/api/__init__.py
  mresponse/applications/api/serializers.py
  mresponse/responses/api/__init__.py
  mresponse/responses/api/serializers.py
  mresponse/responses/api/urls.py
  mresponse/responses/api/views.py
  mresponse/reviews/api/__init__.py
  mresponse/reviews/api/serializers.py
  mresponse/reviews/api/urls.py
  mresponse/reviews/api/views.py
  mresponse/reviews/models.py
  mresponse/reviews/query.py
  setup.cfg
Labels: Back End

#36 Auth0 Frontend Implementation
  README.rst
  mresponse/frontend/app/.env
  mresponse/frontend/app/.env.example
  mresponse/frontend/app/config/webpack.config.dev.js
  mresponse/frontend/app/package.json
  mresponse/frontend/app/src/App.js
  mresponse/frontend/app/src/components/avatar/index.js
  mresponse/frontend/app/src/components/input-field/index.js
  mresponse/frontend/app/src/components/login-form/index.js
  mresponse/frontend/app/src/components/signup-form/index.js
  mresponse/frontend/app/src/components/tag-field/index.js
  mresponse/frontend/app/src/components/toolbar/index.js
  mresponse/frontend/app/src/pages/login/index.js
  mresponse/frontend/app/src/pages/login/login.js
  mresponse/frontend/app/src/pages/profile/profile.js
  mresponse/frontend/app/src/pages/settings/settings.js
  mresponse/frontend/app/src/pages/welcome/index.js
  mresponse/frontend/app/src/pages/welcome/welcome.js
  mresponse/frontend/app/src/pages/welcome/welcome.scss
  mresponse/frontend/app/src/redux/actions/auth.js
  mresponse/frontend/app/src/redux/actions/index.js
  mresponse/frontend/app/src/redux/reducers/auth.js
  mresponse/frontend/app/src/redux/reducers/errors.js
  mresponse/frontend/app/src/redux/reducers/index.js
  mresponse/frontend/app/src/redux/store.js
  mresponse/frontend/app/src/utils/auth-route.js
  mresponse/frontend/app/src/utils/auth.js
  mresponse/frontend/app/src/utils/urls.js
  mresponse/frontend/app/yarn.lock
  mresponse/frontend/urls.py
Labels: Front End

#46 Add Auth0 authentication to the backend
  app.json
  mresponse/api/urls.py
  mresponse/api/views.py
  mresponse/settings/base.py
  mresponse/users/__init__.py
  mresponse/users/api/__init__.py
  mresponse/users/api/serializers.py
  mresponse/users/api/urls.py
  mresponse/users/api/views.py
  mresponse/users/utils.py
  requirements.txt
  setup.cfg
Labels: Back End

#35 Update existing templates to follow new design
  mresponse/frontend/app/public/static/media/firefox.png
  mresponse/frontend/app/public/static/media/mozilla-logo.png
  mresponse/frontend/app/public/static/media/mozilla-logo.svg
  mresponse/frontend/app/public/static/media/welcome-image.png
  mresponse/frontend/app/src/components/avatar/index.js
  mresponse/frontend/app/src/components/buttons/buttons.scss
  mresponse/frontend/app/src/components/forgot-password-form/forgot-form.scss
  mresponse/frontend/app/src/components/highlighted-text/highlighted-text.scss
  mresponse/frontend/app/src/components/input-field/field.scss
  mresponse/frontend/app/src/components/input-field/index.js
  mresponse/frontend/app/src/components/login-form/index.js
  mresponse/frontend/app/src/components/login-form/login-form.scss
  mresponse/frontend/app/src/components/progress-bar/index.js
  mresponse/frontend/app/src/components/progress-bar/progress-bar.scss
  mresponse/frontend/app/src/components/response-card/index.js
  mresponse/frontend/app/src/components/response-card/response-card.scss
  mresponse/frontend/app/src/components/signup-form/index.js
  mresponse/frontend/app/src/components/signup-form/signup-form.scss
  mresponse/frontend/app/src/components/tag-field/field.scss
  mresponse/frontend/app/src/components/tag-field/index.js
  mresponse/frontend/app/src/components/toolbar/index.js
  mresponse/frontend/app/src/components/toolbar/toolbar.scss
  mresponse/frontend/app/src/pages/login/login.js
  mresponse/frontend/app/src/pages/login/login.scss
  mresponse/frontend/app/src/pages/profile/profile.js
  mresponse/frontend/app/src/pages/profile/profile.scss
  mresponse/frontend/app/src/pages/settings/settings.js
  mresponse/frontend/app/src/pages/settings/settings.scss
  mresponse/frontend/app/src/pages/welcome/welcome.js
  mresponse/frontend/app/src/pages/welcome/welcome.scss
  mresponse/frontend/app/src/styles/_vars.scss
  mresponse/frontend/app/src/utils/auth.js
  mresponse/frontend/app/src/utils/urls.js
  mresponse/frontend/app/stories/components.stories.js
  mresponse/frontend/app/stories/pages.stories.js
Labels: Front End

#77 Fix APPEND_SLASH catch all url for the front-end
  mresponse/frontend/urls.py
Labels: Estimate: 1 hour, bug

#80 Fix catch all URL pattern not returning homepage
  mresponse/frontend/urls.py
Labels: Back End

#83 Add moderation model
  mresponse/homepage/api/views.py
  mresponse/moderations/__init__.py
  mresponse/moderations/admin.py
  mresponse/moderations/migrations/0001_initial.py
  mresponse/moderations/migrations/__init__.py
  mresponse/moderations/models.py
  mresponse/responses/admin.py
  mresponse/responses/migrations/0002_auto_20181012_1447.py
  mresponse/responses/migrations/0003_response_approved.py
  mresponse/responses/models.py
  mresponse/responses/query.py
  mresponse/reviews/admin.py
  mresponse/settings/base.py
  mresponse/utils/admin.py
Labels: Back End

#86 Add locking and skipping of the review
  mresponse/responses/api/views.py
  mresponse/reviews/api/serializers.py
  mresponse/reviews/api/urls.py
  mresponse/reviews/api/views.py
  mresponse/reviews/migrations/0002_auto_20181012_1556.py
  mresponse/reviews/models.py
  mresponse/reviews/query.py
  mresponse/settings/base.py
Labels: Back End

#89 Add Auth0 test account details to the dev settings
  README.rst
  mresponse/frontend/app/yarn.lock
  mresponse/settings/dev.py
Labels: Back End

#92 Add karma and response/moderation count to user
  mresponse/moderations/migrations/0002_auto_20181015_1308.py
  mresponse/moderations/models.py
  mresponse/responses/migrations/0004_auto_20181015_1308.py
  mresponse/responses/models.py
  mresponse/settings/base.py
  mresponse/users/admin.py
  mresponse/users/api/serializers.py
  mresponse/users/apps.py
  mresponse/users/migrations/0001_initial.py
  mresponse/users/migrations/__init__.py
  mresponse/users/models.py
  mresponse/users/signal_handlers.py
Labels: Back End

#98 Add moderation API endpoints
  mresponse/api/tests.py
  mresponse/api/urls.py
  mresponse/api/views.py
  mresponse/moderations/api/__init__.py
  mresponse/moderations/api/serializers.py
  mresponse/moderations/api/urls.py
  mresponse/moderations/api/views.py
  mresponse/moderations/migrations/0003_auto_20181016_1533.py
  mresponse/moderations/models.py
  mresponse/responses/api/serializers.py
  mresponse/responses/api/urls.py
  mresponse/responses/api/views.py
  mresponse/responses/query.py
  mresponse/reviews/api/serializers.py
  mresponse/reviews/api/views.py
  mresponse/reviews/query.py
  mresponse/utils/queryset.py
Labels: Back End

#105 Add about and feedback URLs to the API
  mresponse/api/views.py
Labels: Back End

#119 Add skip response and assigning response to user
  mresponse/moderations/api/views.py
  mresponse/responses/api/serializers.py
  mresponse/responses/api/urls.py
  mresponse/responses/api/views.py
  mresponse/responses/migrations/0005_responseassignedtouser.py
  mresponse/responses/models.py
  mresponse/responses/query.py
Labels: Back End

#122 Fix homepage count
  mresponse/homepage/api/views.py
  mresponse/responses/api/views.py
  mresponse/reviews/query.py
Labels: Back End, bug

#127 Add basic auth
  mresponse/api/middleware.py
  mresponse/frontend/app/yarn.lock
  mresponse/settings/base.py
Labels: Back End

#135 Fix lacking response in skipping response
  mresponse/responses/api/views.py
Labels: Back End, bug

#107 Set languages available in the app
  mresponse/api/views.py
Labels: Back End

#140 bug: Check for the PK in the skip response
  mresponse/responses/api/views.py
  mresponse/responses/models.py
Labels: bug

#147 Prioritise languages
  mresponse/reviews/api/views.py
  mresponse/reviews/query.py
Labels: Back End

#174 Add auth0 production settings
  mresponse/frontend/app/.env
  mresponse/frontend/app/src/utils/auth.js
  mresponse/frontend/app/yarn.lock
Labels: Front End
